sort : sort.o
    gcc -o sort sort.o

sort.o : sort.c
    gcc -c -o sort.o sort.c

matrix : matrix.o
    gcc -o matrix matrix.o

matrix.o : matrix.c
    gcc -c -o matrix.o matrix.c

clean :
    rm *.0 sort matrix